// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_revamp/test/features/tv_series/presentation/on_the_air_tv_series_bloc/on_the_air_tv_series_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ditonton_revamp/common/failure.dart' as _i6;
import 'package:ditonton_revamp/feature/tv_series/domain/entities/tv_series.dart'
    as _i7;
import 'package:ditonton_revamp/feature/tv_series/domain/repositories/tv_series_repository.dart'
    as _i2;
import 'package:ditonton_revamp/feature/tv_series/domain/usecases/get_on_the_air_tv_series.dart'
    as _i3;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesRepository_0 extends _i1.SmartFake
    implements _i2.TvSeriesRepository {
  _FakeTvSeriesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetOnTheAirTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvSeries extends _i1.Mock
    implements _i3.GetOnTheAirTvSeries {
  MockGetOnTheAirTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvSeriesRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.TvSeries>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.TvSeries>>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.TvSeries>>>);
}
