// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcbgDQ0tRM_DjmhZ62C29LeiB1H1kUfHg',
    appId: '1:832873063981:web:e7c4d54c3e99c8993f7aa4',
    messagingSenderId: '832873063981',
    projectId: 'ditonton-revamp',
    authDomain: 'ditonton-revamp.firebaseapp.com',
    storageBucket: 'ditonton-revamp.firebasestorage.app',
    measurementId: 'G-V12CVD1VPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNgGCgZpo4AX2aHKo7kc257kV7d7gk08',
    appId: '1:832873063981:android:243bfeb4692eadac3f7aa4',
    messagingSenderId: '832873063981',
    projectId: 'ditonton-revamp',
    storageBucket: 'ditonton-revamp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfY_1RSTl4-c5WTwhTnPrxpkE-F_t8DI',
    appId: '1:832873063981:ios:5dd5a245031e13373f7aa4',
    messagingSenderId: '832873063981',
    projectId: 'ditonton-revamp',
    storageBucket: 'ditonton-revamp.firebasestorage.app',
    iosBundleId: 'com.example.ditontonRevamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfY_1RSTl4-c5WTwhTnPrxpkE-F_t8DI',
    appId: '1:832873063981:ios:5dd5a245031e13373f7aa4',
    messagingSenderId: '832873063981',
    projectId: 'ditonton-revamp',
    storageBucket: 'ditonton-revamp.firebasestorage.app',
    iosBundleId: 'com.example.ditontonRevamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcbgDQ0tRM_DjmhZ62C29LeiB1H1kUfHg',
    appId: '1:832873063981:web:1c04e2cfebd9cfb53f7aa4',
    messagingSenderId: '832873063981',
    projectId: 'ditonton-revamp',
    authDomain: 'ditonton-revamp.firebaseapp.com',
    storageBucket: 'ditonton-revamp.firebasestorage.app',
    measurementId: 'G-7D34YRPJL0',
  );

}