// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_revamp/test/features/tv_series/presentation/add_remove_tv_watchlist_bloc/add_remove_tv_watchlist_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ditonton_revamp/common/failure.dart' as _i7;
import 'package:ditonton_revamp/feature/tv_series/domain/entities/tv_series_detail.dart'
    as _i8;
import 'package:ditonton_revamp/feature/tv_series/domain/repositories/tv_series_repository.dart'
    as _i2;
import 'package:ditonton_revamp/feature/tv_series/domain/usecases/get_tv_series_watchlist_status.dart'
    as _i3;
import 'package:ditonton_revamp/feature/tv_series/domain/usecases/remove_tv_series_watchlist.dart'
    as _i10;
import 'package:ditonton_revamp/feature/tv_series/domain/usecases/save_tv_series_watchlist.dart'
    as _i5;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesRepository_0 extends _i1.SmartFake
    implements _i2.TvSeriesRepository {
  _FakeTvSeriesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTvSeriesWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesWatchListStatus extends _i1.Mock
    implements _i3.GetTvSeriesWatchListStatus {
  MockGetTvSeriesWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvSeriesRepository);

  @override
  _i4.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [SaveTvSeriesWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTvSeriesWatchlist extends _i1.Mock
    implements _i5.SaveTvSeriesWatchlist {
  MockSaveTvSeriesWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvSeriesRepository);

  @override
  _i4.Future<_i6.Either<_i7.Failure, String>> execute(
    _i8.TvSeriesDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, String>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String>>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, String>>);
}

/// A class which mocks [RemoveTvSeriesWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTvSeriesWatchlist extends _i1.Mock
    implements _i10.RemoveTvSeriesWatchlist {
  MockRemoveTvSeriesWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvSeriesRepository);

  @override
  _i4.Future<_i6.Either<_i7.Failure, String>> execute(
    _i8.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, String>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String>>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, String>>);
}
